image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

before_script:
  - npm install

test:
  stage: test
  script:
    - npm run test

preview:
  stage: build
  script:
    - npm run build
    - npm run deploy -- $FTP_USER $FTP_PASSWORD $FTP_HOST
  artifacts:
    paths:
    - dist

pages:
  stage: build
  script:
    - npm run compodoc
  artifacts:
    paths:
    - public
    expire_in: 1h
